import * as moment from "moment";
import { DeliveryTypes, SalesTypes } from "../workflow/workflow-contracts/workflow-contracts.model";
import { PurchaseOrderCapType } from "src/shared/service-proxies/service-proxies";

export const DISPLAYED_COLUMNS: string[] = [
    'select',
    'status',
    'note',
    'PONumber',
    'client',
    'lastUpdate',
    'wfPeriodId',
    'clientContact',
    'consultant',
    'salesType',
    'deliveryType',
    'capType',
    'amount',
    'units',
    'clientRate',
    'totalAmount',
    'amountLeft',
    'estimatedUnitsLeft',
    'startDate',
    'endDate',
    'contractManager',
    'accountManager',
    'actions',
];

export enum EPOStatus {
    AttentionRequired = 'Action required',
    ClientNotified = 'Client notified',
    CMActionRequired = 'CM action required',
    Completed = 'Completed'
}

export const DUMMY_DATA = [
    {
        id: 1,
        status: EPOStatus.AttentionRequired,
        note: 'Some note for PO number, some note.',
        PONumber: 'PL-123456',
        client: 'JN Data',
        lastUpdate: moment(),
        wfPeriodId: '16932/01',
        clientContact: 'Joanna Pietraszewska',
        consultant: 'Matt Nowak',
        salesType: SalesTypes.Recruitment,
        deliveryType: DeliveryTypes.ManagedService,
        capType: PurchaseOrderCapType.CapOnUnits,
        amount: 6000,
        units: 'Days',
        clientRate: 1000,
        clientRateCurrencyId: 1,
        clientRateUnitType: 1,
        totalAmount: 2000,
        amountLeft: 1234,
        estimatedUnitsLeft: 111,
        startDate: moment(),
        endDate: moment(),
        contractManager: 'Joanna Pietraszewska CM',
        accountManager: 'Joanna Pietraszewska AM'
    },
    {
        id: 1,
        status: EPOStatus.AttentionRequired,
        note: 'Some note for PO number, some note.',
        PONumber: 'PL-123456',
        client: 'JN Data',
        lastUpdate: moment(),
        wfPeriodId: '16932/01',
        clientContact: 'Joanna Pietraszewska',
        consultant: 'Matt Nowak',
        salesType: SalesTypes.Recruitment,
        deliveryType: DeliveryTypes.ManagedService,
        capType: PurchaseOrderCapType.CapOnUnits,
        amount: 6000,
        units: 'Days',
        clientRate: 1000,
        clientRateCurrencyId: 1,
        clientRateUnitType: 1,
        totalAmount: 2000,
        amountLeft: 1234,
        estimatedUnitsLeft: 111,
        startDate: moment(),
        endDate: moment(),
        contractManager: 'Joanna Pietraszewska CM',
        accountManager: 'Joanna Pietraszewska AM'
    },
    {
        id: 1,
        status: EPOStatus.AttentionRequired,
        note: 'Some note for PO number, some note.',
        PONumber: 'PL-123456',
        client: 'JN Data',
        lastUpdate: moment(),
        wfPeriodId: '16932/01',
        clientContact: 'Joanna Pietraszewska',
        consultant: 'Matt Nowak',
        salesType: SalesTypes.Recruitment,
        deliveryType: DeliveryTypes.ManagedService,
        capType: PurchaseOrderCapType.CapOnUnits,
        amount: 6000,
        units: 'Days',
        clientRate: 1000,
        clientRateCurrencyId: 1,
        clientRateUnitType: 1,
        totalAmount: 2000,
        amountLeft: 1234,
        estimatedUnitsLeft: 111,
        startDate: moment(),
        endDate: moment(),
        contractManager: 'Joanna Pietraszewska CM',
        accountManager: 'Joanna Pietraszewska AM'
    }
]
