trigger: none

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@0
  inputs:
    command: install
    arguments: '--global @angular/cli'
  displayName: 'install @angular/cli'

- script: |
    yarn
  displayName: 'yarn install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm run prod'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'angular build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: dist
    includeRootFolder: false
  displayName: 'Archive dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
