export const FILTER_LABEL_MAP: { [key: string]: string } = {
	language: 'Language',
	id: 'ID',
	agreementType: 'Type',
	recipientTypeId: 'Recipient',
	legalEntityIds: 'Legal entities',
	legalEntityId: 'Legal entity',
	salesTypeIds: 'Sales type',
	deliveryTypeIds: 'Delivery type',
	contractTypeIds: 'Contract type',
	isEnabled: 'Status',
	status: 'Status',
	linkState: 'Mode',
	lastUpdatedByLowerCaseInitials: 'By',
	mode: 'Mode',
	linkStateAccepted: 'Approval',
	saleManager: 'SM',
	contractManager: 'CM',
};
